spring:
  datasource:
    url: jdbc:h2:mem:userservice
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080

app:
  JwtSecret: qrD6h8K6S9503Q06Y6Rfk21TErImPYqa
  JwtExpirationMs: 86400000
